### ISSUE TITLE
Layering tsparticles on top of tsparticles

### ISSUE THREAD

**Issue by JoshuaKissel** [tsparticles/tsparticles#1334]
**Which version are you using?**
Ex. 1.18.12

**Is the latest version affected?**

- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [ ] React (`react-tsparticles`)

Migrating from particles.js on a Hugo site.

**Describe the solution you'd like**
I was wondering if it's possible to add multiple tsparticles.js to one canvas. I am looking to have the nodes change to different colors on hover (some change to red, some to blue, some to yellow, etc) and figured this would be the best way to go about it.

If this is possible or if this there is a better way to make this happen please let me know.

**Comment by matteobruni** [comment]
Hi @JoshuaKissel,

Every tsParticles instance uses its own canvas, you can stack them using CSS `z-index` but I never recommend this since they could lead to a low-quality result for all the resources used.
I thought about multiple `interactivity` sections but nothing has been done yet. Anyway, you can have different colored particles and using the `interactivity.bubble` changing only opacity and size.
With this configuration, you'll have all the particles having the same fill and hover colors. Having them different I don't think is actually possible but I'll do some checks.
