### ISSUE TITLE
stroke for images/svg particles?

### ISSUE THREAD

**Issue by thewayur** [tsparticles/tsparticles#1400]
Is there anyway to give stroke to images? like stroke is working in circular particles not custom images path.

also i want to know if i can change stroke/color/shadow values on the fly without refreshing the whole particle canvas?
thanks

**Which version are you using?**
1.22.1

 
 
**Which library are you using?**
 
- [ ] jQuery (`jquery-particles`)

**Comment by matteobruni** [comment]
Hi @thewayur,

Probably you are trying to achieve something like this: https://github.com/matteobruni/tsparticles/blob/main/demo/main/public/presets/svgReplace.json

```json
    "shape": {
      "image": {
          "src": "/images/canine.svg",
          "width": 32,
          "height": 32,
          "replaceColor": true
        },
        "type": "image"
    }
```

This is what you need, the `replaceColor` for the image shape options, this will replace every color with the particle color value. Actually is not possible to replace only a subset of colors.

**Comment by thewayur** [comment]
@matteobruni  much much thanks for the reference. now u have provided more examples for experiments :)

ok fine, i m getting that library still have limitations, its fine. I LOVE THIS LIBRARY (i m very new to canvas too)

now 2 big ques:
1. how to  add stroke to them?
2. how to change color on fly(without refreshing whole canvas). please i m new to canvas!

**Comment by matteobruni** [comment]
For stroking the particles you can see this sample: https://codepen.io/matteobruni/pen/XWbBxEm
Changing the color on the fly can be done with the animation like here: https://codepen.io/matteobruni/pen/NWRPKQW

But... If you want to replace the images color it's not supported since the image needs to be loaded for every color and I think the stroke will be a square around the image.

If you need a more complex shape you can draw it yourself, something like this: https://github.com/matteobruni/tsparticles/tree/main/shapes/heart or this https://codepen.io/matteobruni/pen/vYOMmGr but it require some canvas drawing skills

**Comment by thewayur** [comment]
@matteobruni omg, beautiful examples! you are such a lovely person. thanks a lot for such an adorable library.
this is my most fav lib, you are my hero... love from India!!!!!
