### ISSUE TITLE
console.log left in build

### ISSUE THREAD

**Issue by adamalston** [tsparticles/tsparticles#1412]
**Which version are you using?**
1.24.1

**Is the latest version affected?**
- [x] Yes
- [ ] No

**Which library are you using?**

- [ ] Vanilla JS (`tsparticles`)
- [x] React (`react-tsparticles`)
- [ ] Vue.js 2.x (`particles.vue`)
- [ ] Vue.js 3.x (`particles.vue3`)
- [ ] Angular (`ng-particles`)
- [ ] Svelte (`svelte-particles`)
- [ ] Preact (`preact-particles`)
- [ ] Inferno (`inferno-particles`)
- [ ] jQuery (`jquery-particles`)

<details>
 <summary><b>tsParticles Configuration</b></summary>
  
  ```javascript
    N/A
  ```
</details>

**Describe the bug**
`console.log()` production build
I dont know if it was to be expected that the `console.log()` was left in the production build. I only noticed it when testing my app.

**To Reproduce**
1. Go to https://www.adamalston.com/
2. Inspect Element
3. Console
4. See particles object

**Expected behavior**
Remove `console.log()` from production build

**Screenshots**
![image](https://user-images.githubusercontent.com/18297826/112219761-d2864880-8bfb-11eb-8736-f7e8d7a328f8.png)

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
N/A

**Additional context**
I do have an additional question. It seems like the particle speed has been increased significantly between 1.22.x and 1.24.x. What is the reasoning/explanation behind this?

**Comment by matteobruni** [comment]
Thanks for reporting that @adamalston, I didn't noticed that. The `1.24.2` is now live without the `console.dir`. The associated PR is building but the version is live. You can safely update to that 😉

**Comment by adamalston** [comment]
I had a question at the end of the issue that I was hoping someone could answer:
> It seems like the particle speed has been increased significantly between 1.22.x and 1.24.x. What is the reasoning/explanation behind this?

**Comment by matteobruni** [comment]
Ops I didn't noticed that.

I wrote an article about that: https://dev.to/matteobruni/tsparticles-1-23-0-released-4hn5

I'll explain it too:

The formula was wrong, it used random values that makes particles with a speed of `6` have a lower visual speed since it was calculated with a random number multiplied by the horizontal and vertical speed. This could lead to an horizontal speed of `4` and a vertical of `0.5` and the `6` of speed makes no sense.
Emitters with that formula also appears rectangular instead of circular and it was really ugly.

So starting from `1.23.0` the new formula uses `length`/`angle` Vector formulas and the `length` is kept in the randomization process, so only the `angle` changes. This creates emitters with circular shape and a more uniform speed effect.

Starting from `1.24.0` instead, you can set a `{ min: 0, max: 6 }` value to `speed` (also `size.value`, `opacity.value` and `rotate.value`) to have a different `length` (`speed`) too, but this is still a more controlled way of randomizing speed since you can't have slow particles in a fast configuration (example a `{ min: 25, max: 50 }`, before it could happen).

For those using `top`, `left`, `right` and `left` move directions nothing has changed since the `length` is still `±1`.

I wanted to release it in the `2.0.0` version initially, but I found it unnecessary release a major version just for a speed algorithm. What is coming with the current `2.0.0`  version is a massive architecture rework where you can only include what you need for your configuration and nothing more, but it's not ready for production yet.

I'm releasing faster because I'm detaching some ready features from that version that could be brought here easily.

In the end I thought that the new speed formula will bring more benefits than issues.

**Comment by matteobruni** [comment]
The new values are:

| | new x | new y | old x | old y |
|-|-|-|-|-|
| top | 0 | -1 | 0 | -1 |
| top right | <img src="https://user-images.githubusercontent.com/176620/112229420-3aa45100-8c33-11eb-8f7e-d34708e53c6b.png" alt="sqrt(2)/2" height="50" /> | <img src="https://user-images.githubusercontent.com/176620/112229481-57d91f80-8c33-11eb-8c2e-2fdf9eeb9605.png" alt="-sqrt(2)/2" height="50" /> | 0.5 | -0.5 |
| right | 1 | 0 | 1 | 0 |
| bottom right | <img src="https://user-images.githubusercontent.com/176620/112229420-3aa45100-8c33-11eb-8f7e-d34708e53c6b.png" alt="sqrt(2)/2" height="50" /> | <img src="https://user-images.githubusercontent.com/176620/112229420-3aa45100-8c33-11eb-8f7e-d34708e53c6b.png" alt="sqrt(2)/2" height="50" /> | 0.5 | 0.5 |
| bottom | 0 | 1 | 0 | 1 |
| bottom left | <img src="https://user-images.githubusercontent.com/176620/112229481-57d91f80-8c33-11eb-8c2e-2fdf9eeb9605.png" alt="-sqrt(2)/2" height="50" /> | <img src="https://user-images.githubusercontent.com/176620/112229420-3aa45100-8c33-11eb-8f7e-d34708e53c6b.png" alt="sqrt(2)/2" height="50" /> | -0.5 | 0.5 |
| left | -1 | 0 | -1 | 0 |
| top left | <img src="https://user-images.githubusercontent.com/176620/112229481-57d91f80-8c33-11eb-8c2e-2fdf9eeb9605.png" alt="-sqrt(2)/2" height="50" /> | <img src="https://user-images.githubusercontent.com/176620/112229481-57d91f80-8c33-11eb-8c2e-2fdf9eeb9605.png" alt="-sqrt(2)/2" height="50" /> | -0.5 | -0.5 |

Using `none` instead of a couple of random values, it's

```javascript
const angle = Math.random() * Math.PI * 2;

horizontal = Math.cos(angle);
vertical = Math.sin(angle);
```

**Comment by adamalston** [comment]
Thanks for the explanation, the math behind the change seems interesting. Also sounds like performance will see an improvement due to the circular emitter and speed being more linear - not that it was bad before.
