### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by noraj** [tsparticles/tsparticles#1859]
**Which version are you using?**

Not related to the code.

**Is the latest version affected?**

Not a bug.

*You can checkout latest version [here](https://www.npmjs.com/package/tsparticles)*

Not related to the code.

**Which library are you using?**

Not related to the code.

PS: why is the custom issue template is the same a the bug report one?

## Description

There is no changelog available, so one having to update tsparticle can't know if a breaking change will occur.

For example, I updated `tsparticles  ^1.18.11  →  ^1.32.0` and now I have an error in my gulp task because `node_modules/tsparticles/dist/tsparticles.min.js` doesn't exist anymore (because it has been renamed to `node_modules/tsparticles/tsparticles.min.js`).

## Solution

Create a CHANGELOG.

**Comment by matteobruni** [comment]
Hi @noraj,

I have a change log file but I didn’t notice it’s broken since 1.18, it’s maintained by lerna but something broke that

The broken change log is here: https://github.com/matteobruni/tsparticles/blob/main/engine/CHANGELOG.md

Anyway I add all informations in PR and GH releases, the one you need is this: https://github.com/matteobruni/tsparticles/pull/1719

I’ll fix the change log ASAP, thanks for reporting

**Comment by noraj** [comment]
> The broken change log is here: https://github.com/matteobruni/tsparticles/blob/main/engine/CHANGELOG.md

So it's in the engine folder 😃  thx

**Comment by matteobruni** [comment]
Changelog is working again with lerna, closing the issue
