### ISSUE TITLE
Not able to use multiple particles canvas on single screen

### ISSUE THREAD

**Issue by rhythmbhiwani** [tsparticles/tsparticles#3993]
### Contact Details

rhythmbhiwani@gmail.com

### What happened?

I wanted to show user option to select between different particles background with a preview. But then I noticed that when rendering only one container for particles, it renders correctly, but when I try to render multiple containers only one is rendered which also not 100% accurate everytime. 

After inspecting, I noticed that it adds a div with id `tsparticles` to each container, but we can have only one element with a id, so the DOM renders the particles to only the first container found.

Here is codesandbox link to replicate this
https://codesandbox.io/s/react-tsparticles-issue-8mwz8i?file=/src/App.js

Please check and let me know is it a bug, or is there any workaround to it.

### Version

1.42.4

### Which library are you using?

React.js (react-tsparticles, react-particles-js)

### tsParticles Configuration

```json
https://codesandbox.io/s/react-tsparticles-issue-8mwz8i?file=/src/App.js
```

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I've seen there's a missing property in the documentation, the `id` property, which overrides the default `"tsparticles"` value.

Anyway, I do not recommend using more than one container since it could worsen the performance. You can achieve multiple effects using particle groups. The only thing that is not particle customizable is mouse interaction (for now).

**Comment by rhythmbhiwani** [comment]
Seems working, thanks a lot. Should add it in the documentation
