### ISSUE TITLE
Wrong Installation Command for ReactJS

### ISSUE THREAD

**Issue by tryraisins** [tsparticles/tsparticles#4610]
### Contact Details

tryraisins@gmail.com

### What do you need?

the installation code in the readme (`npm install react-particles`)is incorrect/incomplete. To successfully install all dependencies I had to run: `npm install react-particles tsparticles react-tsparticles`

### tsParticles Version

 react-tsparticles:  2.2.1,   tsparticles: 2.2.1, react-particles: 2.2.1

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
I know that `tsparticles` is not in the README.md but that's because you could use `tsparticles-slim` or any other preset, and those packages don't require `tsparticles` installed.

Install both `react-particles` and `react-tsparticles` is redundant. Only one of them is necessary, since they're the same library with a different name.
