### ISSUE TITLE
Generic Issue

### ISSUE THREAD

**Issue by FleetAdmiralJakob** [tsparticles/tsparticles#4855]
### Contact Details

jakob.roessner@outlook.de

### What do you need?

How can I update from version 1.42.2?!

I updated the packages already but then the website stops working. Pls say to me how I have to change the params/options etc. to update to the latest version

### tsParticles Version

1.14.2/2.6.0

### Which library are you using?

React.js (react-particles, react-tsparticles, react-particles-js)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
You can find the `2.0.x` release notes with the instructions [here](https://github.com/matteobruni/tsparticles/releases?q=2.0.6&expanded=true) or [here](https://dev.to/tsparticles/tsparticles-205-is-out-breaking-changes-ahead-keeping-the-1x-support-2n63)

About the GitHub release changelog, the `tsparticles@next` tag is not existing anymore since v2 is actually the current version
