### ISSUE TITLE
Opacity and custom shapes

### ISSUE THREAD

**Issue by caprica** [tsparticles/tsparticles#4995]
### What do you need?

 I am using the React implementation of this library.

I want to use a custom shape implementation for a particle. It is mostly working, I can see my new particle rendering.

The issue/question I have is how to properly deal with opacity, because the opacity seems to be controlled by some external factor rather than the implementation of my shape drawing function.

The effect I'm going for is a semi-transparent circle, overlaid with solid colour, 100% white, text.

The effect achieved is that no matter what I do, the overlaid text is not solid colour, e.g. whites look gray.

Here is my shape implementation:

```typescript
export const bubbleTextShape = (
    context: CanvasRenderingContext2D,
    particle: IParticle,
    radius: number,
    opacity: number,
    delta: IDelta,
    pixelRatio: number,
) => {
    context.save()

    context.globalAlpha = opacity

    const bubbleText = particle.shapeData as BubbleTextShape
    const bubbleTextParticle = particle as BubbleTextParticle

    const text = "Hello World"

    // It seems to render the circle anyway without this beginPath and fill
    context.beginPath()
    context.arc(0, 0, radius, 0, Math.PI * 2)
    context.fill()

    const fontStyle = bubbleText.style ?? 'normal'
    const fontWeight = bubbleText.weight ?? '400'
    const fontSize = radius / 3.2
    const font = bubbleText.font

    context.font = `${fontStyle} ${fontWeight} ${fontSize}px ${font}`
    context.textAlign = 'center'
    context.textBaseline = 'middle'

    context.globalAlpha = 1.0
    context.fillStyle = 'white'
    context.fillText(text, 0, 0)

    context.restore()
}
```

In my particles config, I set opacity to 0.5.

If I set the opacity in the particles config to 1, then:

- I only see the circle, not the overlaid text
- Setting context.globalAlpha = 0.5 in the shape function has no effect on the circle

Screenshot shows semi-transparent circle when config opacity is 0.5. The overlaid text is not white.

![image](https://github.com/matteobruni/tsparticles/assets/1385879/ba5810aa-9bdf-4520-b972-cffe5a7ebcfe)

I'm trying to do the equivalent of this:

```html
<canvas style="background-color: black" id="myCanvas" width="578" height="250"></canvas>
    <script>
      var canvas = document.getElementById('myCanvas');
      var context = canvas.getContext('2d');

      context.fillStyle = '#0000ff';
      context.globalAlpha = 0.5;

      context.beginPath();
      context.arc(100, 120, 75, 0, Math.PI * 2);
      context.arc(300, 120, 75, 0, Math.PI * 2);
      context.fill();

      context.font = 'normal bold 30px sans';
      context.fillStyle = 'white';

      context.globalAlpha = 0.5;
      context.fillText("Bad", 50, 130);

      context.globalAlpha = 1.0;
      context.fillText("Good", 250, 130);

    </script>
</canvas>
```
![image](https://github.com/matteobruni/tsparticles/assets/1385879/287a5174-7663-467f-91b6-ffb9745906c1)

Any clues as to where I am going wrong?

### tsParticles Version

2.9.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
Can you please provide also your config or a full working repro so I can check what's going on?

**Comment by caprica** [comment]
OK, I will do, it will take a little time as I have to factor out code that can't be public, but I will follow-up.

**Comment by matteobruni** [comment]
I've changed your code to work fine using the right functions, you can see a sample here: https://codepen.io/matteobruni/pen/NWOVMgd?editors=0010

The `IShapeDrawer` interface is better than the single function, so you can check other available functionalities, like the `afterEffect` like in this case.

```
export class BubbleTextShape implements IShapeDrawer {
  draw(
    context: CanvasRenderingContext2D,
    particle: IParticle,
    radius: number,
    opacity: number,
    delta: IDelta,
    pixelRatio: number
  ): void {
    context.arc(0, 0, radius, 0, Math.PI * 2);
  }

  afterEffect(
    context: CanvasRenderingContext2D,
    particle: IParticle,
    radius: number,
    opacity: number,
    delta: IDelta,
    pixelRatio: number
  ): void {
    const bubbleText = particle.shapeData;
    const bubbleTextParticle = particle;

    const text = "Hello World";

    const fontStyle = bubbleText.style ?? "normal";
    const fontWeight = bubbleText.weight ?? "400";
    const fontSize = radius / 3.2;
    const font = bubbleText.font;

    context.font = `${fontStyle} ${fontWeight} ${fontSize}px ${font}`;
    context.textAlign = "center";
    context.textBaseline = "middle";

    context.globalAlpha = 1.0;
    context.fillStyle = "white";
    context.fillText(text, 0, 0);
  }
}
```

The circle is drawn using the standard `draw` function, since it's all you need there, the draw function is already prepared with all the particles options, and the draw function should only draw stuff, not changing the context values.

The `afterEffect` function is called after the `draw` function, so the particle can get something additional from a more generic function, like a custom white text. The only thing the `afterEffect` is sharing with the `draw` method is the position in the canvas. Everything in the `afterEffect` is your duty, from the `save/restore` to the `fill` function. The `draw` function instead is already in a `save/restore` context and the `fill` function is called after that, if needed.

https://particles.js.org/docs/interfaces/tsParticles_Engine.Core_Interfaces_IShapeDrawer.IShapeDrawer.html

This is the url describing the `IShapeDrawer` interface, you can also init the particle there, with some values that you may need for customization, instead of checking them every time in `draw` or `afterEffect` functions

**Comment by caprica** [comment]
Thank you very much, I will go through this soon.

I had just finished pushing a repo that shows the issue, I guess that's not needed anymore :-)

https://github.com/caprica/tsparticles-custom-shape

**Comment by matteobruni** [comment]
You can use that repo to test the updated code, if there's something that is not working it's easier to check out other issues

**Comment by caprica** [comment]
Works perfectly, thank you very much.
