### ISSUE TITLE
[Bug]: `_array` and `_zArray` leaking when particles are destroyed by life updater

### ISSUE THREAD

**Issue by longnguyen2004** [tsparticles/tsparticles#5101]
### What happened?

When the life updater destroys a particle, it uses the `particle.destroy()` method

https://github.com/matteobruni/tsparticles/blob/c6e7ed52f0306467dc22f90619d4e821bd9d07cd/updaters/life/src/LifeUpdater.ts#L119-L122

...which does not remove the particle from the `_array` and `_zArray` array, causing memory leaks

### tsParticles Version

2.11.1

### tsParticles Configuration

```json
See relevant discussion: https://github.com/matteobruni/tsparticles/discussions/5100
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
The `destroy` method is not responsible for removing the particle from the array. The issue is here:

https://github.com/matteobruni/tsparticles/blob/c6e7ed52f0306467dc22f90619d4e821bd9d07cd/engine/src/Core/Particles.ts#L326

There is no `zArray` filter here. The fix is already part of the `2.12.0` PR here: #5071
