### ISSUE TITLE
Feature Request: Deterministic rendering independent of system clock

### ISSUE THREAD

**Issue by KCFindstr** [tsparticles/tsparticles#5355]
### Contact Details

mimi@rabimimi.com

### What is your request?

Hi team,

I am trying to render some particles with https://www.remotion.dev/. Currently, the main blocker for me is that remotion requires the rendering to be deterministic - it shouldn't rely on the system clock, but a custom hook that provides the current frame number, and all threads should render identical content if providing the same random seed and frame number. I am wondering if it is possible to consider adding *any* of the following features:

- Injecting a custom clock instead of using the system clock
- Setting animation state to a specific timestamp
- Exposing update logic to allow manual updates

I believe this awesome library should work with remotion if any of the features is supported!

### tsParticles Version

3.0.2

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by matteobruni** [comment]
This feature is available in 3.5.0 (out now) with this new function:

```
function setAnimationFunctions(
    nextFrame: (callback: FrameRequestCallback) => number,
    cancel: (handle: number) => void,
): void
```

and you use it like this:

```
function setAnimationFunctions(
    (cb: FrameRequestCallback): number => requestAnimationFrame(cb),
    (idx: number): void => cancelAnimationFrame(idx),
);
```

You must pass a function that has a `DOMHighResTimeStamp` parameter in the nextFrame function, like `requestAnimationFrame`, and the cancelFunction must stop the loop as well using the id returned by the nextFrame function. These numbers can be dummy, but are required to work. A `DOMHighResTimeStamp` valid value can be seen with `performance.now()`, it's required since it's used for calculations between frames. Setting `smooth: true` in options prevent this behavior as much as possible, but the parameter is mandatory anyway.

For taking control of the frames you can set a variable to `performance.now()` initially and add to it a value for each frame (calculated in base of the framerate you need). If you need more help about it, let me know.
