### ISSUE TITLE
Impossible to fully navigate Configuration Options Documentation

### ISSUE THREAD

**Issue by Shuna322** [tsparticles/tsparticles#773]
The most annoying thing that I have right now with this project is bad documentation.

For some unknown reasons, export functions from the demo site, etc have different keys and undocumented features.

Example:
On page 
https://github.com/matteobruni/tsparticles/wiki/tsParticles-Options-Particles
We can see `lineLinked` key but it's actually the `links`.

And when we look at `links` documentation we cant see all the features. Where is `blink`, `consent`, `shadow`, `triangles` and many other keys. Most of the time I can't even understand what the function does, how to use it even while comparing.

The documentation needs a good rewrite in my opinion.

**Comment by matteobruni** [comment]
Hi @Shuna322,

Thanks for the report, I'm aware that the wiki is a little behind and it will be fixed as soon as possible, hopefully in a few weeks.

I'm working on a visual editor (#534) that will have all the options so it's easier to understand what each option does.

The website also needs a refresh (#753) but this can wait for now.

If you want to see all the available options you can have a look here: https://particles.matteobruni.it/docs/interfaces/_options_interfaces_ioptions_.ioptions.html

It's the auto-generated documentation from code comments. Some of them don't have a description but in a future release, I'll fix them, hope to fix them before 1.18.0.

I'll give this issue maximum priority since the documentation is really important and sometimes I forgot about it.

Obviously, if you need some help don't hesitate to ask, I'll answer ASAP

**Comment by matteobruni** [comment]
Just to explain the options you mentioned:

`line_linked`, `lineLinked`, `links` are all valid

I'll detail here the properties of that section:

- `blink`: it's a boolean value and if set to `true` the link line will have a different color each frame, creating a blinking effect
- `consent`: it's a boolean value and if set to `true` all link lines will have the same random color

These two properties work only with the `color` set to `"random"`.

- `shadow`: is an object to enable links shadow effect. A big note on this feature, drawing shadows on canvas reduces a lot the frame rate so use this with caution

The `shadow` object has these properties:

- `blur`: a number to specify the shadow blur value
- `color`: the same color object/value you can specify everywhere sets the link shadow color
- `enable`: the boolean value to enable or not the feature

Now let's talk about `triangles`

- `triangles`: is an object to enable the filling of the "triangles" made by the link lines.

This object has these properties:

- `color`: the same color object/value you can specify everywhere sets the link triangle color
- `enable`: the boolean value to enable or not the feature
- `opacity`: the color opacity value; defaults to 0.1

The `links` feature reduces a little the performance since it can be a long task to iterate through all links. I don't recommend it with long-distance links.
