### ISSUE TITLE
Question: Any plans for bundle size improvements?

### ISSUE THREAD

**Issue by rschristian** [tsparticles/tsparticles#958]
I came across this lib while looking around the ol' `particles.js` stuff. Only, the current bundle size is well outside the realm of what I could reasonably consider: https://bundlephobia.com/result?p=preact-particles@1.18.4. To add a 50kb lib to Preact would be the antithesis of what it's trying to do really. 

Are there any plans to remove old and bloated code/dependencies like Lodash and really focus on cutting down library size?

**Comment by matteobruni** [comment]
Yes, the bundle size is one critical issue I'm trying to solve.
The core library doesn't use `lodash`, it's used in the Preact/React/Inferno version to update the component to every options change. It's not `lodash` fault anyway, the core `tsParticles` library is still big but I'm trying to create a more composable library so everyone can add the features they want to use.

**Comment by rschristian** [comment]
That `lodash` import does make up 10% of the lib's size, so I wouldn't say it's innocent. If you're looking for a deep comparison alternative to use with `.memo` or something, `react-fast-compare` is probably the best out there. Only 1.7kb minified, 706b minzipped.

**Comment by matteobruni** [comment]
The `2.0.0` version will have `fast-deep-equal`. I preferred this to `react-fast-compare` since it's the parent library and is still actively supported and has itself a `react` version. Performances seem the same, so it should be fine with less size.

The main goal of `2.0.0` version is also composability, you can choose yourself what feature you want to include
