### ISSUE TITLE
Docs: "Dependency free" should be removed

### ISSUE THREAD

**Issue by rschristian** [tsparticles/tsparticles#962]
The current documentation states that the package is dependency free, but that is not correct. I'm not sure if it is just outdated but so long as the [dependencies section of the package](https://github.com/matteobruni/tsparticles/blob/623f7680174d9e50f6cca4a00291f700f1899105/core/main/package.json#L135) is not empty then this is not true.

The asterisk states these aren't strictly needed but that is not the way the ecosystem works. If something is listed as a dependency then that tells NPM that it is necessary and will be always be installed alongside this package.

If something isn't strictly necessary then it can moved into being a peer dependency instead.

I'd make a PR myself but as I only speak English and some German I cannot (correctly) update all the documentation pages.

**Comment by matteobruni** [comment]
I fixed the `dependencies` in the `package.json`, `tslib` were not required in browser since it was bundled by webpack and `pathseg` is used only with the polygon mask, that will become an external plugin in `v2.0.0`, has been moved to `optionalDependencies`.

That should be fine without changing the README.

P.S. Removing `tslib` reduced size by `5kb` of the unminified file.
